
<script type="text/javascript">
 
$(document).ready(function()
{
	$("#showcase").awShowcase(
	{
		content_width:			700,
		content_height:			470,
		fit_to_parent:			false,
		auto:					true,
		interval:				3000,
		continuous:				false,
		loading:				true,
		tooltip_width:			200,
		tooltip_icon_width:		32,
		tooltip_icon_height:	32,
		tooltip_offsetx:		18,
		tooltip_offsety:		0,
		arrows:					true,
		buttons:				true,
		btn_numbers:			false,
		keybord_keys:			true,
		mousetrace:				false, /* Trace x and y coordinates for the mouse */
		pauseonover:			true,
		stoponclick:			false,
		transition:				'fade', /* hslide/vslide/fade */
		transition_delay:		0,
		transition_speed:		500,
		show_caption:			'onload', /* onload/onhover/show */
		thumbnails:				false,
		thumbnails_position:	'outside-last', /* outside-last/outside-first/inside-last/inside-first */
		thumbnails_direction:	'vertical', /* vertical/horizontal */
		thumbnails_slidex:		1, /* 0 = auto / 1 = slide one thumbnail / 2 = slide two thumbnails / etc. */
		dynamic_height:			false, /* For dynamic height to work in webkit you need to set the width and height of images in the source. Usually works to only set the dimension of the first slide in the showcase. */
		speed_change:			true, /* Set to true to prevent users from swithing more then one slide at once. */
		viewline:				false, /* If set to true content_width, thumbnails, transition and dynamic_height will be disabled. As for dynamic height you need to set the width and height of images in the source. */
		custom_function:		null /* Define a custom function that runs on content change */
	});
});

</script>

<?php if($this->offer_reco != 0) { ?>
<div id="showcase" class="showcase">
            <?php for ($i = 0; $i <= $this->offer_reco-1; $i++) { ?>
		<div class="showcase-slide">
                    <div class="showcase-content">
			<img src="img/pages/download.png" alt="01" />
                        <div class="showcase-content-wrapper">
                            <div class="showcase-main-content">
                                <div class="wrapper-left">
                                    <h2 class="cyan"><?php echo $offer_name[$i]; ?></h2>
                                    <p class="wrapper-text">
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et 
                                        dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip 
                                        ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu 
                                        fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in.
                                    </p>
                                </div>

                                <div class="wrapper-right">
                                    <div class="price"><h3><?php echo $offer_old_price[$i]; ?>zł</h3><h2 class="cyan"><?php echo $offer_new_price[$i]; ?>zł</h2></div>

                                    <a href="<?php echo $this->url('podglad', array('link'=>$offer_link[$i])); ?>" class="wrapper-link">sprawdź >></a>
                                </div>
                             </div>
                        </div> 
                    </div>
		</div>
            <?php } ?>
	</div>

<?php } else {
            echo '<div class="offer-zero pages p-offer-zero-reco white"><h2>Błąd #0002</br>Brak ofert w mieście <b>'.$this->city.'</b></h2></div>';
        }
?>       


<div class="width">
    <div id="city-grid">
        <div class="fl"><?php echo $this->region.' -> '.$this->city; ?></div><div class="fr"><a href="<?php echo $this->url('select', array('action'=>'zmiana')); ?>">Zmień Miasto</a></div>
    </div>
</div>

<div id="grid">
    <div class="width">
        <div id="normal">
            <?php for ($i = 0; $i <= count($offer_name)-1; $i++) { ?>
            <div class="normal">
                <div class="mosaic-block fade">
			<a href="<?php echo $this->url('podglad', array('link'=>$offer_link[$i])); ?>" class="mosaic-overlay">
				<div class="details">
                                    <div class="mosaic-discribe">
					<h4>Rabat 25%</h4>
                                        <p>- Słowa kluczowe,</br>
                                            - słowa kluczowe2.
                                        </p>
                                    </div>    
				</div>
			</a>
			<div class="mosaic-backdrop"><img class="ri" src="<?php echo $this->basePath() . '/../data/upload/'; ?><?php echo $photo_src[$i]; ?>"/></div>
		</div>
                <div class="normal-move"><a href="<?php echo $this->url('podglad', array('link'=>$offer_link[$i])); ?>">przejdź do oferty</a></div>
                <div class="normal-price">
                    <h3><?php echo $offer_old_price[$i]; ?>zł</h3><h2><?php echo $offer_new_price[$i]; ?>zł</h2>
                </div>
                <div class="normal-details">
                    
                    <div class="offer-title-normal"><?php echo '<a href="'.$this->url('podglad', array('link'=>$offer_link[$i])).'">'.$offer_name[$i].'</a>'; ?></div>
                </div>
            </div>
            <div class="normal-space"></div>
            <?php } ?>
        </div>
        <?php 
                if($this->offer_reco != 0) { ?>
         <div id="recommendedoffer">
            
                    <?php for ($i = 0; $i <= $this->offer_reco-1; $i++) { ?>
                <div class="reco">
                
                <div class="offer-title-reco"><?php echo $offer_name[$i]; ?></div>
                <a href='<?php echo $this->url('podglad', array('link'=>$offer_link[$i])); ?>'><img src="<?php echo $this->basePath() . '/../data/upload/'; ?><?php echo $photo_src[$i]; ?>"/></a>
                <div class="reco-price">
                    <h3><?php echo $offer_old_price[$i]; ?>zł</h3><h2><?php echo $offer_new_price[$i]; ?>zł</h2>
                </div>
                <p>
                        Obiekt wita gości pięknymi widokami na jezioro Czos. Oferuje możliwość doskonałego wypoczynku. Usytuowany w romantycznym ogrodzie, dysponuje 60 doskonale wyposażonymi pokojami gościnnymi. Z balkonu każdego z nich można podziwiać wspaniały widok na okolicę. Na terenie ogrodu znajduje się piękny staw, nad którym można spacerować lub grillować. Jest też możliwość zagrania w bilard czy porzucania do tarczy rzutkami z nowo poznanymi znajomymi.</p>
                    <div class="reco-down">Pobrano: <strong>83</strong></div>
                    <div class="reco-button">
                        <a href="<?php echo $this->url('podglad', array('link'=>$offer_link[$i])); ?>">przejdź do oferty</a>
                    </div>    
                        
            </div>
                
        </div> 
        <?php }
                }else {
                    echo '<div class="offer-zero-none"><h3>Błąd #0002</br>Brak ofert w mieście <b>'.$this->city.'</b></h3></div>';
                }
                ?>
    </div>     
</div>

<script>
    $(document).ready(function(){
       $('.recommended').bxSlider({
            auto: true,
          });
      });
</script>