                              			
				<div class="content-module">
				
					<div class="content-module-heading cf">
					
						<h3 class="fl"><?php echo $this->translate('Oferty oczekujące') ?></h3>
						<span class="fr expand-collapse-text"><?php echo $this->translate('Schowaj') ?></span>
						<span class="fr expand-collapse-text initial-expand"><?php echo $this->translate('Wysuń') ?></span>
					
					</div> <!-- end content-module-heading -->
					
					
					<div class="content-module-main">
					
						
                                           <table class="tablesorter" id="options">
						
							<thead>
						
								<tr>
									<th><input type="checkbox" id="table-select-all"></th>
									<th class="sort"><?php echo $this->translate('Nazwa') ?></th>
									<th class="sort"><?php echo $this->translate('Miasto') ?></th>

									<th><?php echo $this->translate('Akcje') ?></th>
								</tr>
							
							</thead>
	
						
							
							<tbody>
                                                            <?php for ($i = 0; $i <= count($offername)-1; $i++) { ?>
								<tr>
									<td><input type="checkbox"></td>
									<td><?php echo $this->escapeHtml($offername[$i]);?></td>
									<td><?php echo $this->escapeHtml($cityname[$i]);?></td>
									<td>
										<a href="<?php echo $this->url('waiting', array('action'=>'accept', 'id' => $offerid[$i], 'city' => $cityname[$i])) ?>" class="table-actions-button ic-table-accept"></a>
										<a href="<?php echo $this->url('waiting', array('action'=>'refuse', 'id' => $offerid[$i], 'city' => $cityname[$i])) ?>" class="table-actions-button ic-table-refuse"></a>
									</td>
								</tr>                                                               
                                                            <?php } ?>    
                                                        </tbody>	
						</table>
                                                       
                                            
                                                <div class="spaces"></div>    
					</div> <!-- end content-module-main -->
				
				</div> <!-- end content-module -->
				
			

			