                              			
				<div class="content-module">
				
					<div class="content-module-heading cf">
					
						<h3 class="fl"><?php echo $this->translate('Oferty oczekujące') ?></h3>
						<span class="fr expand-collapse-text"><?php echo $this->translate('Schowaj') ?></span>
						<span class="fr expand-collapse-text initial-expand"><?php echo $this->translate('Wysuń') ?></span>
					
					</div> <!-- end content-module-heading -->
					
					
					<div class="content-module-main">
					
						
                                            Oferta została odrzucona
                                                       
                                            
                                                <div class="spaces"></div>    
					</div> <!-- end content-module-main -->
				
				</div> <!-- end content-module -->
				
			

			