                              			
				<div class="content-module">
				
					<div class="content-module-heading cf">
					
						<h3 class="fl"><?php echo $this->translate('Wiadomości') ?></h3>
						<span class="fr expand-collapse-text"><?php echo $this->translate('Schowaj') ?></span>
						<span class="fr expand-collapse-text initial-expand"><?php echo $this->translate('Wysuń') ?></span>
					
					</div> <!-- end content-module-heading -->
					
					
					<div class="content-module-main">
                                            <table class="tablesorter" id="options">
						
							<thead>
						
								<tr>
									<th><input type="checkbox" id="table-select-all"></th>
									<th class="sort"><?php echo $this->translate('Temat') ?></th>
									<th class="sort"><?php echo $this->translate('Od') ?></th>
									<th class="sort"><?php echo $this->translate('Data') ?></th>
									<th><?php echo $this->translate('Akcje') ?></th>
								</tr>
							
							</thead>
	
						
							
							<tbody>
                                                            <?php foreach($this->messages as $message) { ?>
                                                                
								<tr id="flip<?php echo $message->id; ?>">
									<td><input type="checkbox"></td>
									<td><?php echo $message->subject; ?></td>
                                                                        <td><?php echo $message->from; ?></a></td>
									<td><?php echo gmdate("Y-m-d H:i:s",$message->date);?></td>
									<td>
										<a href="<?php echo $this->url('offer', array('action'=>'delete', 'id' => $offerid[$i])) ?>" class="table-actions-button ic-table-delete"></a>
									</td>
								</tr>  
                                                                
                                                                <tr>
                                                                    
                                                                    <th colspan="5" class="message"><div id="panel<?php echo $message->id; ?>"><?php echo $message->text; echo count($this->messages); ?></div></th>
                                                                </tr>
                                                                
                                                            <?php } ?>    
                                                        </tbody>	
						</table>  
					</div> <!-- end content-module-main -->
				
				</div> <!-- end content-module -->
				
<?php foreach($this->messages as $message) { ?> 			
<style>
#panel<?php echo $message->id; ?>,#flip<?php echo $message->id; ?>
{
    padding:5px;
    text-align:left;
    text-transform: none;
}
#panel<?php echo $message->id; ?>
{
    padding:20px;
    display:none;
    color: #fff;
}
</style>
<script> 
   
        $(document).ready(function(){
        $("#flip<?php echo $message->id; ?>").click(function(){
        $("#panel<?php echo $message->id; ?>").slideToggle("fast");
        });
        });
       
</script>
<?php } ?> 
