                              			
				<div class="content-module">
				
					<div class="content-module-heading cf">
					
						<h3 class="fl"><?php echo $this->translate('Logi kodów') ?></h3>
						<span class="fr expand-collapse-text"><?php echo $this->translate('Schowaj') ?></span>
						<span class="fr expand-collapse-text initial-expand"><?php echo $this->translate('Wysuń') ?></span>
					
					</div> <!-- end content-module-heading -->
					
					
					<div class="content-module-main">
					
						<?php foreach ($this->logs as $log) {
                                                    $date = date('d-m-Y G:i:s', $log->date);
                                                    if($log->action == 'success') {
                                                        echo '<div class="confirmation-box round">'.$log->disc.' <div class="fr"><b>Miasto:</b>'.$log->city.' <b>'.$date.'</b></div></div>';
                                                    } elseif($log->action == 'fail-nocode') {
                                                        echo '<div class="error-box round">'.$log->disc.' <div class="fr"><b>Miasto:</b>'.$log->city.' <b>'.$date.'</b></div></div>';
                                                    }
                                                }
                                                       
                                                ?>
                                                <div class="spaces"></div>    
					</div> <!-- end content-module-main -->
				
				</div> <!-- end content-module -->
				
			

			