
 <script>
$(function() {
var availableTags = [
<?php foreach ($addresses as $addres) : ?>
"<?php echo $this->escapeHtml($addres->company);?>",
<?php endforeach; ?>      
];
$( "#tags" ).autocomplete({
source: availableTags
});
});
</script>

				<div class="content-module">
				
					<div class="content-module-heading cf">
					
						<h3 class="fl"><?php echo $this->translate('Dodaj ofertę') ?></h3>
						<span class="fr expand-collapse-text"><?php echo $this->translate('Schowaj') ?></span>
						<span class="fr expand-collapse-text initial-expand"><?php echo $this->translate('Wysuń') ?></span>
					
					</div> <!-- end content-module-heading -->
					
					
					<div class="content-module-main">
                                            <div class="steps">
                                                <ul>
                                                  <li class="step step-1">
                                                    <a class="comp" href="#"><strong>Krok 1</strong><br />podaj podstawowe dane</a>
                                                  </li>
                                                  <li class="step step-2">
                                                    <a class="current" href="#"><strong>Krok 2</strong><br />wybierz dane firmy</a>
                                                  </li>
                                                  <li class="step step-3">
                                                    <a href="#"><strong>Krok 3</strong><br />dodaj zdjęcia</a>
                                                  </li>
                                                  <li class="step step-4">
                                                    <a href="#"><strong>Krok 4</strong><br />wybierz miasta</a>
                                                  </li>
                                                </ul>
                                            </div> 
                                            
                                            <?php
                                                $form = $this->form;
                                                $form->prepare();
                                                echo $this->form()->openTag($form);
                                                
                                                echo $this->formLabel($form->get('company'));
                                                
                                                if($this->id) {
                                                    echo $this->formInput($form->get('company')->setValue($this->id));
                                                } else {
                                                    echo $this->formInput($form->get('company'));
                                                }
                                                echo $this->formElementErrors($form->get('company'));
                                                echo '<div class="mr-button">'.$this->formInput($form->get('submit')).'<a href="'.$this->url('offer', array('action'=>'companyadd', 'link'=>$this->link)).'" class="button2 round blue image-right ic-right-arrow mr-left">Dodaj Firmę</a></div>';
                                                echo $this->form()->closeTag();
                                            ?>
					
					</div> <!-- end content-module-main -->
				
				</div> <!-- end content-module -->
				
			

			